# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Counseling Resources
subtitle: To infinity and beyond
title_separator: "@"
name: Sandy Lin
email: counselloryuki@gmail.com
description: Some collections of counseling resources, including college, career and school counseling materials for you to explore possibilities.

# twitter_username: username
github_username: counselloryuki
minimal_mistakes_skin: aqua

breadcrumbs: true
logo: /favicon.ico
locale: en-US
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

url: https://counselloryuki.github.io
repository: counselloryuki/counselloryuki.github.io

## search
# search_full_content: true
search: true
search_provider: algolia

algolia:
  nodes_to_index: 'p,blockquote,li,div,em,strong,sup,a,table'
  application_id: ZAMMRAVB0O
  index_name: counselloryuki_github
  search_only_api_key: 653e48e4be7cfc3eabb8f94017094a25
  powered_by: true

###

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sandy Lin"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Some collections of counseling resources, including college, career and school counseling materials for you to explore possibilities."
  links:
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/sandy0"
    - label: "Facebook"
      icon: "fab fa-facebook-square"
      url: "https://facebook.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com"
    - label: "GitHub"
      icon: "fab fa-github-square"
      url: "https://github.com/counselloryuki"
    - label: "Instagram"
      icon: "fab fa-instagram-square"
      url: "https://instagram.com/"
    - label: "Youtube"
      icon: "fab fa-youtube"
      url: "https://youtube.com/"

footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/sandy0"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-github-square"
      url: "https://github.com/counselloryuki"
    - label: "Youtube"
      icon: "fab fa-youtube"
      url: "https://youtube.com/"
    - label: "Reddit"
      icon: "fab fa-reddit-square"
      url: "https://reddit.com/"
    - label: "Facebook"
      icon: "fab fa-facebook-square"
      url: "https://facebook.com"
    - label: "Instagram"
      icon: "fab fa-instagram-square"
      url: "https://instagram.com/"
    - label: "Discord"
      icon: "fab fa-discord"
      url: "https://discord.com/"

comments:
  provider: "disqus"
  disqus:
    shortname: "counselloryuki"

collections:
  colleges:
    output: true
    permalink: /:collection/:path/

defaults:
  # _colleges
  - scope:
      path: ""
      type: colleges
    values:
      layout: single
      author_profile: false
      comments: true
      share: true
      sidebar:
        nav: college-list
        title: Shortcuts
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-M71FB8LV7M"
    anonymize_ip: false # default

after_footer_scripts:
  - /assets/js/custom.js
